import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../server/app.mjs';
import {hashPassword,verifyPassword,validateEntry} from '../server/security.mjs';
// Behavioral in-memory double. An actual Atlas connection is tested separately by the owner.
function database(){const tables=new Map();const match=(row,query)=>Object.entries(query).every(([key,value])=>value?.$gt?row[key]>value.$gt:row[key]===value);return{collection(name){if(!tables.has(name))tables.set(name,[]);const rows=tables.get(name);return{
 async findOne(q){return rows.find(r=>match(r,q))||null;},
 async insertOne(row){if(rows.some(r=>r._id===row._id||(name==='users'&&r.email===row.email)))throw Object.assign(Error('duplicate'),{code:11000});rows.push({...row});},
 async updateOne(q,update,{upsert}={}){let row=rows.find(r=>match(r,q));if(!row&&upsert){row={...q,...update.$setOnInsert};rows.push(row);}if(row){Object.assign(row,update.$set);for(const [k,n] of Object.entries(update.$inc||{}))row[k]=(row[k]||0)+n;}},
 async deleteOne(q){const i=rows.findIndex(r=>match(r,q));if(i===-1)return{deletedCount:0};rows.splice(i,1);return{deletedCount:1};},
 find(q){return{sort(){return this;},async toArray(){return rows.filter(r=>match(r,q)).map(({_id,userId,...r})=>r).sort((a,b)=>b.completedAt-a.completedAt);}}}
 };}};}
function request(path,{method='GET',body,cookie,origin='http://localhost:3000'}={}){return new Request('http://localhost:3000'+path,{method,headers:{'content-type':'application/json',origin,...(cookie?{cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});}
const entry={id:'memory-1',title:'A little walk',reflection:'Birdsong',completedAt:Date.now(),recordedMinutes:15,source:'Gemma',photo:null};
async function signup(app,email){const response=await app(request('/api/auth/signup',{method:'POST',body:{email,password:'a-long-private-passphrase'}}));assert.equal(response.status,200);return response.headers.get('set-cookie').split(';')[0];}
test('passwords use salted hashes and verify correctly',async()=>{const hash=await hashPassword('long-secret-password');assert.equal(await verifyPassword('long-secret-password',hash),true);assert.equal(await verifyPassword('wrong-secret-password',hash),false);assert.notEqual(hash,await hashPassword('long-secret-password'));});
test('journal requires sign-in and refuses cross-origin writes',async()=>{const app=createApp({db:database()});assert.equal((await app(request('/api/journal'))).status,401);assert.equal((await app(request('/api/auth/signup',{method:'POST',origin:'https://evil.example',body:{}}))).status,403);});
test('two accounts cannot read or delete one another’s entries; upsert is idempotent',async()=>{const app=createApp({db:database()});const alice=await signup(app,'alice@example.com'),bob=await signup(app,'bob@example.com');for(let i=0;i<2;i++)assert.equal((await app(request('/api/journal',{method:'POST',cookie:alice,body:{...entry,userId:'attacker'}}))).status,200);let a=await app(request('/api/journal',{cookie:alice}));assert.equal((await a.json()).entries.length,1);let b=await app(request('/api/journal',{cookie:bob}));assert.equal((await b.json()).entries.length,0);assert.equal((await app(request('/api/journal/memory-1',{method:'DELETE',cookie:bob,body:{}}))).status,404);assert.equal((await app(request('/api/journal/memory-1',{method:'DELETE',cookie:alice,body:{}}))).status,200);});
test('session expires, logout revokes access, and production cookie is secure',async()=>{const db=database(),app=createApp({db,env:{NODE_ENV:'production'}});const response=await app(request('/api/auth/signup',{method:'POST',body:{email:'user@example.com',password:'private-passphrase-123'}}));assert.match(response.headers.get('set-cookie'),/__Host-grassquest=.*HttpOnly; SameSite=Strict.*Secure/);const cookie=response.headers.get('set-cookie').split(';')[0];assert.equal((await app(request('/api/journal',{cookie}))).status,200);await app(request('/api/auth/logout',{method:'POST',cookie,body:{}}));assert.equal((await app(request('/api/journal',{cookie}))).status,401);const next=await signup(app,'second@example.com');const session=await db.collection('sessions').findOne({});session.expiresAt=new Date(0);assert.equal((await app(request('/api/journal',{cookie:next}))).status,401);});
test('login works with normalized email and rejects incorrect passwords',async()=>{const app=createApp({db:database()});await signup(app,'USER@example.com');const ok=await app(request('/api/auth/login',{method:'POST',body:{email:'user@example.com',password:'a-long-private-passphrase'}}));assert.equal(ok.status,200);const bad=await app(request('/api/auth/login',{method:'POST',body:{email:'user@example.com',password:'incorrect-password'}}));assert.equal(bad.status,401);});
test('entry validation blocks invalid timestamps, photos and long reflections',()=>{assert.throws(()=>validateEntry({...entry,photo:'javascript:alert(1)'}));assert.throws(()=>validateEntry({...entry,recordedMinutes:500}));assert.throws(()=>validateEntry({...entry,reflection:'x'.repeat(1001)}));assert.equal(validateEntry(entry).title,entry.title);});
test('auth rate limiting returns 429',async()=>{const app=createApp({db:database()});for(let i=0;i<20;i++)await app(request('/api/auth/login',{method:'POST',body:{}}));assert.equal((await app(request('/api/auth/login',{method:'POST',body:{}}))).status,429);});
test('missing database keeps guest mode and reports cloud unavailable',async()=>{const app=createApp();assert.equal((await (await app(request('/api/auth/me'))).json()).cloud,false);assert.equal((await app(request('/api/journal'))).status,503);});
