import {randomBytes, scrypt as scryptCallback, timingSafeEqual, createHash} from 'node:crypto';
import {promisify} from 'node:util';
const scrypt=promisify(scryptCallback);
const options={N:32768,r:8,p:3,maxmem:64*1024*1024};
export const digest=value=>createHash('sha256').update(value).digest('hex');
export async function hashPassword(password){const salt=randomBytes(16).toString('hex');const key=await scrypt(password,salt,64,options);return salt+':'+key.toString('hex');}
export async function verifyPassword(password,stored){const [salt,hex]=stored.split(':');const actual=await scrypt(password,salt,64,options);const expected=Buffer.from(hex,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected);}
export function credentials(input){const email=typeof input.email==='string'?input.email.trim().toLowerCase():'';const password=input.password;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254||typeof password!=='string'||password.length<12||password.length>128)throw new Error('Use a valid email and a password of 12–128 characters.');return {email,password};}
export function validateEntry(input){const string=(name,max,required=false)=>{const value=input[name];if(typeof value!=='string'||value.length>max||(required&&!value.trim()))throw Error('Invalid '+name);return value;};const id=string('id',64,true);if(!/^[a-zA-Z0-9-]{1,64}$/.test(id))throw Error('Invalid id');const title=string('title',120,true),reflection=string('reflection',1000);const completedAt=Number(input.completedAt),recordedMinutes=Number(input.recordedMinutes);if(!Number.isFinite(completedAt)||completedAt<0||completedAt>Date.now()+60000||!Number.isInteger(recordedMinutes)||recordedMinutes<1||recordedMinutes>90)throw Error('Invalid time');const source=['Gemma','Sample quest'].includes(input.source)?input.source:'Sample quest';let photo=null;if(input.photo!=null){if(typeof input.photo!=='string'||input.photo.length>1500000||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(input.photo))throw Error('Invalid image');photo=input.photo;}return {id,title,reflection,completedAt,recordedMinutes,source,photo};}
